import type { Project } from "./types";

const placeholderArchitecture = {
  summary: "PLANNED — Architecture documentation will be added as implementation milestones are completed.",
  nodes: [],
  connections: [],
} as const;

function plannedProject(
  slug: string,
  title: string,
  subtitle: string,
  technologies: Project["technologies"],
): Project {
  return {
    slug,
    title,
    subtitle,
    summary: "PLANNED — This project record is ready for objectives, evidence, architecture decisions, and measured outcomes as work begins.",
    status: "planned",
    phase: "Discovery",
    updatedAt: "2026-07-23",
    role: "Lead Engineer",
    objectives: ["PLANNED — Define scope and success criteria", "PLANNED — Document architecture decisions", "PLANNED — Capture reproducible evidence"],
    overview: ["PLANNED — The project experience is prepared and will be populated as engineering work is completed."],
    technologies,
    timeline: [{ date: "Planned", title: "Discovery and design", description: "PLANNED — Confirm requirements, constraints, and validation approach.", status: "planned" }],
    architecture: placeholderArchitecture,
    challenges: [],
    lessonsLearned: [],
    gallery: [],
    videos: [],
    codeExamples: [],
    downloads: [],
    certifications: [],
    futureRoadmap: ["PLANNED — Complete discovery", "PLANNED — Build the first validated milestone", "PLANNED — Publish implementation evidence"],
    relatedProjectSlugs: [],
  };
}

const enterpriseHomeLab: Project = {
  slug: "enterprise-home-lab",
  title: "Enterprise Home Lab",
  subtitle: "A phased enterprise reference environment for infrastructure, identity, network security, observability, and recovery engineering.",
  summary: "IN PROGRESS — A consulting-style reference design for a segmented enterprise laboratory. The documentation baseline and project platform are implemented; infrastructure deployment, validation evidence, and operational metrics remain explicitly tracked as in progress or planned.",
  status: "active",
  phase: "Foundation Design",
  updatedAt: "2026-07-23",
  duration: "Ongoing",
  role: "Infrastructure and Security Engineer",
  objectives: [
    "IMPLEMENTED — Establish a version-controlled engineering report, architecture baseline, and evidence standards.",
    "IN PROGRESS — Define segmented management, server, client, lab, and DMZ security zones with explicit trust boundaries.",
    "PLANNED — Deploy centralized identity, DNS, DHCP, certificate, logging, monitoring, backup, and recovery services.",
    "PLANNED — Validate firewall policy, authentication, name resolution, address allocation, telemetry delivery, backup restoration, and recovery procedures.",
  ],
  overview: [
    "EXECUTIVE SUMMARY — Project RedForge is developing an enterprise home lab as a controlled environment for infrastructure administration, security engineering, monitoring, and incident-analysis practice. The current deliverable is the approved logical design and documentation system. It is not a representation of a completed production environment.",
    "BUSINESS GOALS — The lab is intended to provide repeatable engineering scenarios, reduce risk through isolated testing, demonstrate traceable technical decision-making, and create a durable platform for future Active Directory, Splunk, vulnerability-management, automation, and threat-hunting projects.",
    "ENVIRONMENT OVERVIEW — The target state uses a virtualized compute layer behind a policy-enforcing firewall. Dedicated VLANs separate management, servers, clients, security testing, and DMZ workloads. Identity, DNS, DHCP, certificate services, monitoring, and backup are introduced through phased change records.",
    "OPERATING MODEL — Every capability moves through Planned, In Progress, Implemented, and Validated states. Implementation claims require configuration records and sanitized evidence; performance or reliability claims require recorded measurements. No such metrics are asserted in this report.",
    "INFRASTRUCTURE COMPONENTS — PLANNED. A dedicated firewall, a Proxmox virtualization host, Windows Server and Linux guests, Windows 11 and Kali Linux endpoints, and a Splunk-based monitoring tier form the documented target platform. Hardware models and capacity values remain intentionally unspecified until procurement and validation are complete.",
    "SERVER INVENTORY — PLANNED. DC01 is reserved for Active Directory Domain Services and DNS, MGMT01 for DHCP and administration, SIEM01 for Splunk, LNX01 for Linux services, and PKI01 for future certificate services. These names are design identifiers only and are not evidence of deployed systems.",
    "SERVICES INVENTORY — PLANNED. Active Directory Domain Services, DNS, DHCP, centralized logging, SIEM analysis, backup, and administrative access are planned. Certificate services and hybrid-cloud connectivity remain future capabilities.",
    "SECURITY STACK — IN PROGRESS. The design combines firewall policy enforcement, VLAN isolation, least-privilege administration, centralized identity, endpoint logging, Splunk analysis, backup controls, and documented trust boundaries. Product configuration and control validation remain pending.",
    "MONITORING STACK — PLANNED. Windows Event Logs, Sysmon telemetry, Linux system logs, and firewall events will feed a centralized Splunk pipeline. No ingestion rate, retention, detection, or coverage metrics are asserted.",
    "IDENTITY SERVICES — PLANNED. A single-forest Active Directory design will provide centralized authentication and policy management. Administrative tiers, service accounts, Group Policy, and recovery procedures require implementation and testing.",
    "DNS — PLANNED. Active Directory-integrated DNS is the target for internal name resolution. Forwarding, scavenging, logging, and recovery settings remain to be validated.",
    "DHCP — PLANNED. Centralized DHCP scopes will align with approved VLANs and reserve infrastructure addresses. Scope options, exclusions, failover, and lease policy remain undecided.",
    "CERTIFICATE SERVICES — FUTURE. An offline-root and issuing-CA pattern is under consideration. No certificate authority or enterprise PKI is represented as deployed.",
    "LOGGING PIPELINE — PLANNED. Endpoint and infrastructure telemetry will traverse controlled network paths to SIEM01, where parsing, retention, alerting, and access controls will be tested before operational use.",
    "BACKUP AND DISASTER RECOVERY — PLANNED. The target strategy includes versioned configuration exports, scheduled virtual-machine backups, protected copies outside the primary datastore, documented recovery dependencies, and periodic restoration exercises. Recovery time and recovery point objectives remain undefined until workload criticality and measured restore performance are available.",
    "REFERENCES — VERIFIED SOURCES. The report links to Microsoft, Netgate, Proxmox, and Splunk documentation used to frame the design. References inform the architecture; they do not constitute implementation evidence.",
  ],
  technologies: [
    { name: "Documentation Baseline — Implemented", category: "platform", description: "Typed project record, editable diagrams, status taxonomy, and evidence placeholders are version controlled." },
    { name: "Proxmox VE — Planned", category: "platform", description: "Target virtualization platform for Windows and Linux workloads; deployment evidence pending." },
    { name: "pfSense Firewall — Planned", category: "security", description: "Target routing, VLAN termination, policy enforcement, DHCP relay/service, VPN, and traffic logging role." },
    { name: "Management VLAN — In Progress", category: "infrastructure", description: "Designated administrative plane for hypervisor, firewall, and management interfaces." },
    { name: "Server VLAN — In Progress", category: "infrastructure", description: "Target zone for domain, certificate, logging, monitoring, and application services." },
    { name: "Client VLAN — In Progress", category: "infrastructure", description: "Target zone for managed Windows 11 workstations and user policy testing." },
    { name: "Lab VLAN — In Progress", category: "security", description: "Isolated target zone for Kali Linux, security tooling, and controlled testing." },
    { name: "DMZ — Planned", category: "security", description: "Restricted target zone for future externally exposed laboratory services." },
    { name: "Windows Server — Planned", category: "infrastructure", description: "Target platform for AD DS, DNS, DHCP, and AD CS roles." },
    { name: "Linux Server — Planned", category: "infrastructure", description: "Target platform for infrastructure utilities, automation, and selected monitoring services." },
    { name: "Windows 11 — Planned", category: "infrastructure", description: "Target managed endpoint for domain join, policy, certificate, logging, and security validation." },
    { name: "Kali Linux — Planned", category: "security", description: "Target isolated assessment workstation; use limited to authorized lab validation." },
    { name: "Active Directory Domain Services — Planned", category: "security", description: "Target identity authority for accounts, computers, groups, Kerberos, LDAP, and Group Policy." },
    { name: "DNS and DHCP — Planned", category: "infrastructure", description: "Target internal name resolution and controlled address allocation with documented dependencies." },
    { name: "Active Directory Certificate Services — Future", category: "security", description: "Future internal PKI for certificate enrollment, service identity, and trust testing." },
    { name: "Splunk Enterprise — Planned", category: "observability", description: "Target SIEM and logging platform for Windows, Linux, firewall, DNS, DHCP, and identity telemetry." },
    { name: "Backup Repository — Planned", category: "infrastructure", description: "Target protected backup location with retention and restoration procedures." },
    { name: "Hybrid Cloud Connection — Future", category: "cloud", description: "Future controlled extension for cloud identity, logging, and network-security scenarios." },
  ],
  timeline: [
    { date: "Jul 2026", title: "Documentation and report platform", description: "IMPLEMENTED — Established the reusable project experience, typed content model, authoring standards, and editable SVG architecture package.", status: "complete" },
    { date: "Current", title: "Logical architecture and segmentation", description: "IN PROGRESS — Defining VLANs, trust boundaries, service dependencies, server inventory, and traffic-flow requirements.", status: "active" },
    { date: "Next", title: "Firewall and virtualization foundation", description: "PLANNED — Install the hypervisor and firewall, create initial networks, record configurations, and validate administrative access.", status: "planned" },
    { date: "Planned", title: "Identity and core network services", description: "PLANNED — Deploy Windows Server, AD DS, DNS, DHCP, managed clients, and administrative policy.", status: "planned" },
    { date: "Planned", title: "Logging and security monitoring", description: "PLANNED — Deploy Splunk, define source onboarding, validate transport, and document retention decisions.", status: "planned" },
    { date: "Future", title: "PKI, resilience, and hybrid cloud", description: "FUTURE — Evaluate AD CS, backup restoration exercises, recovery runbooks, and a controlled cloud connection.", status: "planned" },
  ],
  architecture: {
    summary: "IN PROGRESS — The target logical design places an Internet edge and firewall before DMZ, management, server, client, and lab VLANs. Identity and infrastructure services remain in the server zone; monitoring receives controlled telemetry across trust boundaries.",
    nodes: [
      { id: "internet", label: "Internet", type: "network", description: "EXTERNAL — Untrusted upstream network." },
      { id: "firewall", label: "Firewall", type: "security", description: "PLANNED — Routing, segmentation, policy, DHCP, VPN, and network logging." },
      { id: "dmz", label: "DMZ", type: "network", description: "PLANNED — Restricted zone for future published services." },
      { id: "management", label: "Management Network", type: "network", description: "IN PROGRESS — Administrative interfaces and controlled operator access." },
      { id: "server-vlan", label: "Server VLAN", type: "network", description: "IN PROGRESS — Identity, network, monitoring, and platform services." },
      { id: "client-vlan", label: "Client VLAN", type: "network", description: "IN PROGRESS — Managed Windows 11 workstations." },
      { id: "lab-vlan", label: "Lab VLAN", type: "network", description: "IN PROGRESS — Isolated Kali Linux and authorized test systems." },
      { id: "domain-controller", label: "Domain Controller", type: "server", description: "PLANNED — Windows Server providing AD DS and integrated DNS." },
      { id: "dhcp", label: "DHCP Service", type: "service", description: "PLANNED — Scoped address allocation and option management." },
      { id: "certificate-authority", label: "Certificate Authority", type: "service", description: "FUTURE — Internal certificate enrollment and trust services." },
      { id: "splunk", label: "Splunk / SIEM", type: "security", description: "PLANNED — Centralized ingestion, search, dashboards, and detections." },
      { id: "linux-server", label: "Linux Server", type: "server", description: "PLANNED — Utility, automation, and telemetry workload." },
      { id: "windows-client", label: "Windows 11 Workstation", type: "client", description: "PLANNED — Managed domain endpoint." },
      { id: "kali", label: "Kali Linux", type: "client", description: "PLANNED — Isolated authorized assessment endpoint." },
      { id: "cloud", label: "Future Cloud Connection", type: "cloud", description: "FUTURE — Controlled hybrid identity, logging, and network integration." },
    ],
    connections: [
      { from: "internet", to: "firewall", label: "Untrusted edge" },
      { from: "firewall", to: "dmz", label: "Restricted inbound policy" },
      { from: "firewall", to: "management", label: "Administrative policy" },
      { from: "firewall", to: "server-vlan", label: "Service policy" },
      { from: "firewall", to: "client-vlan", label: "User egress and service access" },
      { from: "firewall", to: "lab-vlan", label: "Isolated test policy" },
      { from: "server-vlan", to: "domain-controller", label: "AD DS and DNS" },
      { from: "server-vlan", to: "dhcp", label: "Address services" },
      { from: "server-vlan", to: "certificate-authority", label: "Future PKI" },
      { from: "client-vlan", to: "domain-controller", label: "Authentication and policy" },
      { from: "lab-vlan", to: "kali", label: "Authorized testing" },
      { from: "firewall", to: "splunk", label: "Network telemetry" },
      { from: "domain-controller", to: "splunk", label: "Identity and DNS logs" },
      { from: "server-vlan", to: "cloud", label: "Future hybrid connection" },
    ],
  },
  challenges: [
    { title: "Enterprise realism within finite resources", context: "IN PROGRESS — The target design must represent enterprise boundaries without claiming production scale or resilience.", resolution: "Use phased capacity planning, explicit workload priorities, resource reservations where justified, and evidence-based scaling decisions." },
    { title: "Service dependency sequencing", context: "IN PROGRESS — Identity, DNS, DHCP, PKI, logging, backup, and monitoring have ordering and recovery dependencies.", resolution: "Maintain a dependency map, deploy core network services before dependent workloads, and validate each phase before adding the next service." },
    { title: "Trust-boundary clarity", context: "IN PROGRESS — Permissive laboratory rules would reduce the value of segmentation exercises.", resolution: "Adopt default-deny inter-zone policy, document required flows, and approve exceptions against named services and validation cases." },
    { title: "Evidence without sensitive disclosure", context: "IMPLEMENTED — Engineering records must demonstrate work without exposing credentials, private addressing, secrets, or unsafe configurations.", resolution: "Use sanitized diagrams, redaction review, scoped screenshots, and placeholders until publishable evidence is available." },
  ],
  lessonsLearned: [
    { title: "Documentation is a control", insight: "IMPLEMENTED — Status-qualified records prevent planned capabilities from being represented as deployed or validated." },
    { title: "Boundaries precede workloads", insight: "IN PROGRESS — VLANs, administrative paths, and permitted flows should be defined before services are placed into zones." },
    { title: "Identity depends on foundational services", insight: "PLANNED VALIDATION — AD DS design must account for DNS, time synchronization, certificate, backup, and recovery dependencies." },
    { title: "Recovery claims require exercises", insight: "PLANNED VALIDATION — Backups alone do not demonstrate recoverability; restoration procedures and measured tests are required." },
  ],
  gallery: [
    { src: "/projects/enterprise-home-lab/diagrams/network-topology.svg", alt: "Planned Enterprise Home Lab network topology showing Internet, firewall, DMZ, management, server, client, and lab security zones", caption: "IN PROGRESS — Target network topology and VLAN separation. This is a design artifact, not implementation evidence." },
    { src: "/projects/enterprise-home-lab/diagrams/logical-architecture.svg", alt: "Planned logical architecture showing identity, DNS, DHCP, certificate, logging, and monitoring services", caption: "IN PROGRESS — Logical service architecture with planned identity and observability dependencies." },
    { src: "/projects/enterprise-home-lab/diagrams/security-zones.svg", alt: "Planned security zones and trust boundaries for the Enterprise Home Lab", caption: "IN PROGRESS — Security-zone classification and intended trust boundaries." },
    { src: "/projects/enterprise-home-lab/diagrams/traffic-flow.svg", alt: "Planned traffic flows between client, identity, firewall, SIEM, and external services", caption: "PLANNED — Required traffic-flow categories; ports and rule identifiers await implementation." },
    { src: "/projects/enterprise-home-lab/diagrams/vlan-layout.svg", alt: "Planned VLAN layout for management, server, client, lab, and DMZ networks", caption: "IN PROGRESS — VLAN purpose model. VLAN identifiers and subnets remain placeholders." },
    { src: "/projects/enterprise-home-lab/diagrams/trust-boundaries.svg", alt: "Planned trust boundaries separating external, administrative, enterprise, and security-testing systems", caption: "IN PROGRESS — Trust-boundary model used to guide default-deny policy." },
    { src: "/projects/enterprise-home-lab/diagrams/rack-elevation.svg", alt: "Planned rack elevation showing firewall, virtualization host, switching, backup, and reserved capacity", caption: "PLANNED — Conceptual rack elevation; hardware units and placement are not implementation evidence." },
    { src: "/projects/enterprise-home-lab/diagrams/hybrid-cloud.svg", alt: "Future hybrid cloud layout connecting the laboratory firewall and server network to a cloud environment", caption: "FUTURE — Conceptual cloud connection reserved for a later approved phase." },
    { alt: "Enterprise Home Lab firewall configuration screenshot placeholder", caption: "PLACEHOLDER — Real firewall configuration evidence will be added after implementation and redaction review." },
    { alt: "Enterprise Home Lab server inventory screenshot placeholder", caption: "PLACEHOLDER — Real virtualization and server inventory evidence has not been captured." },
    { alt: "Enterprise Home Lab Splunk telemetry screenshot placeholder", caption: "PLACEHOLDER — Logging pipeline and SIEM evidence will be added only after validated ingestion." },
  ],
  videos: [
    { title: "Architecture review", description: "PLANNED — A guided design review will be recorded after architecture approval." },
    { title: "Implementation walkthrough", description: "PLACEHOLDER — No deployment walkthrough exists because the infrastructure milestone is not complete." },
  ],
  codeExamples: [{
    title: "Planned validation manifest",
    language: "yaml",
    description: "DESIGN EXAMPLE — A proposed machine-readable inventory for future connectivity validation; not executed evidence.",
    code: "environment: enterprise-home-lab\nstatus: planned\nzones:\n  - management\n  - server\n  - client\n  - lab\n  - dmz\nchecks:\n  - dns-resolution\n  - dhcp-allocation\n  - identity-authentication\n  - telemetry-delivery\n  - backup-restoration\n",
  }],
  downloads: [
    { title: "Network topology SVG", description: "Editable RedForge target-state network topology.", format: "SVG", url: "/projects/enterprise-home-lab/diagrams/network-topology.svg" },
    { title: "Logical architecture SVG", description: "Editable identity, infrastructure, and monitoring service design.", format: "SVG", url: "/projects/enterprise-home-lab/diagrams/logical-architecture.svg" },
    { title: "Microsoft AD DS overview", description: "Official reference for Active Directory Domain Services concepts.", format: "Reference", url: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/active-directory-overview" },
    { title: "Microsoft AD CS overview", description: "Official reference for future certificate-services design.", format: "Reference", url: "https://learn.microsoft.com/en-us/windows-server/identity/ad-cs/active-directory-certificate-services-overview" },
    { title: "Netgate VLAN documentation", description: "Official reference for planned pfSense VLAN configuration.", format: "Reference", url: "https://docs.netgate.com/pfsense/en/latest/vlan/index.html" },
    { title: "Proxmox VE administration guide", description: "Official platform administration reference.", format: "Reference", url: "https://pve.proxmox.com/pve-docs/pve-admin-guide.pdf" },
    { title: "Splunk Enterprise documentation", description: "Official reference for planned logging and SIEM services.", format: "Reference", url: "https://docs.splunk.com/Documentation/Splunk/latest/Admin/StartSplunk" },
  ],
  certifications: [{ name: "CompTIA Network+", issuer: "CompTIA" }, { name: "Microsoft Windows Server", issuer: "Microsoft Learn" }],
  futureRoadmap: [
    "IN PROGRESS — Approve VLAN purposes, trust boundaries, dependency map, and traffic-flow matrix.",
    "PLANNED — Install and baseline the firewall and virtualization platform with sanitized configuration records.",
    "PLANNED — Deploy the domain controller, AD DS, integrated DNS, DHCP, and the first managed Windows 11 workstation.",
    "PLANNED — Deploy Linux services and Splunk, then validate the logging pipeline from firewall, Windows, DNS, and identity sources.",
    "PLANNED — Implement protected backups, document restoration order, and execute recovery exercises before stating recovery capability.",
    "FUTURE — Evaluate AD CS, DMZ workloads, additional domain-controller resilience, vulnerability management, and hybrid cloud connectivity.",
  ],
  relatedProjectSlugs: ["active-directory-lab", "splunk-detection-lab", "network-engineering"],
};

export const projects = [
  enterpriseHomeLab,
  plannedProject("active-directory-lab", "Active Directory Lab", "Identity, policy, authentication, and administrative controls.", [{ name: "Windows Server — Planned", category: "infrastructure" }]),
  plannedProject("splunk-detection-lab", "Splunk Detection Lab", "Telemetry ingestion, investigation, dashboards, and detection workflows.", [{ name: "Splunk — Planned", category: "observability" }]),
  plannedProject("python-automation", "Python Automation", "Operational tooling, validation, and repeatable engineering workflows.", [{ name: "Python — Planned", category: "automation" }]),
  plannedProject("aws-security", "AWS Security", "Cloud identity, logging, networking, and least-privilege engineering.", [{ name: "AWS — Planned", category: "cloud" }]),
  plannedProject("threat-hunting", "Threat Hunting", "Evidence-driven investigation and defensible analytical conclusions.", [{ name: "Splunk — Planned", category: "observability" }]),
  plannedProject("vulnerability-management", "Vulnerability Management", "Asset visibility, prioritization, remediation, and validation.", [{ name: "Nessus — Planned", category: "security" }]),
  plannedProject("network-engineering", "Network Engineering", "Routing, segmentation, services, and resilient network operations.", [{ name: "pfSense — Planned", category: "infrastructure" }]),
] satisfies readonly Project[];

export type ProjectSlug = (typeof projects)[number]["slug"];

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
