import type { Project } from "./types";
import {
  currentEnterpriseHomeLab,
  enterpriseActiveDirectory,
  enterpriseSecurityMonitoring,
} from "./current-projects";

const placeholderArchitecture = {
  summary: "PLANNED — Architecture documentation will be added as implementation milestones are completed.",
  nodes: [],
  connections: [],
} as const;

function plannedProject(
  slug: string,
  title: string,
  subtitle: string,
  technologies: Project["technologies"],
): Project {
  return {
    slug,
    title,
    subtitle,
    summary: "PLANNED — This project record is ready for objectives, evidence, architecture decisions, and measured outcomes as work begins.",
    status: "planned",
    phase: "Discovery",
    updatedAt: "2026-07-23",
    role: "Lead Engineer",
    snapshot: { startDate: "Not started", operationalSystems: "0 verified", validationStatus: "Planned" },
    validation: [{ label: "Validation begins after the first implemented milestone.", status: "planned" }],
    engineeringRecords: [],
    objectives: ["PLANNED — Define scope and success criteria", "PLANNED — Document architecture decisions", "PLANNED — Capture reproducible evidence"],
    overview: ["PLANNED — The project experience is prepared and will be populated as engineering work is completed."],
    technologies,
    timeline: [{ date: "Planned", title: "Discovery and design", description: "PLANNED — Confirm requirements, constraints, and validation approach.", status: "planned" }],
    architecture: placeholderArchitecture,
    challenges: [],
    lessonsLearned: [],
    gallery: [],
    videos: [],
    codeExamples: [],
    downloads: [],
    certifications: [],
    futureRoadmap: ["PLANNED — Complete discovery", "PLANNED — Build the first validated milestone", "PLANNED — Publish implementation evidence"],
    relatedProjectSlugs: [],
  };
}

const enterpriseHomeLab: Project = {
  slug: "enterprise-home-lab",
  title: "Enterprise Home Lab",
  subtitle: "A phased enterprise reference environment for infrastructure, identity, network security, observability, and recovery engineering.",
  summary: "IN PROGRESS — The documentation baseline, Microsoft identity foundation, and centralized Windows telemetry pipeline are implemented. Network segmentation, member services, backup validation, and resilience remain explicitly tracked as in progress or planned.",
  status: "active",
  phase: "Security Telemetry",
  updatedAt: "2026-07-26",
  duration: "Ongoing",
  role: "Infrastructure and Security Engineer",
  snapshot: {
    startDate: "July 2026",
    operationalSystems: "4 verified",
    validationStatus: "Telemetry verified",
  },
  validation: [
    { label: "RF-DC01 Active Directory Domain Services deployment documented.", status: "verified" },
    { label: "RF-DC01 Windows Security Event forwarding confirmed.", status: "verified" },
    { label: "RF-WIN11-01 Sysmon forwarding confirmed.", status: "verified" },
    { label: "Splunk ingestion and controlled SPL retrieval validated.", status: "verified" },
    { label: "DNS resilience and recovery validation remain pending.", status: "pending" },
    { label: "Group Policy validation remains pending.", status: "pending" },
  ],
  engineeringRecords: [
    { id: "RF-DC01", title: "RF-DC01 Server Establishment Log", href: "/documentation/server-establishment-log" },
    { id: "ENG-010", title: "Centralized Telemetry Pipeline Deployment", href: "/documentation/eng-010-centralized-telemetry-pipeline-deployment" },
    { id: "ENG-011", title: "Data-Driven Enterprise Home Lab Topology", href: "/documentation/eng-011-data-driven-enterprise-home-lab-topology" },
  ],
  retrospective: {
    biggestChallenge: "Establishing reliable Sysmon event-channel collection on RF-WIN11-01 without reinstalling the endpoint telemetry stack.",
    solutionSelected: "Trace the forwarding failure to the service permission boundary and run the Splunk Universal Forwarder under Local System.",
    tradeoffsConsidered: "The change restored collection quickly, but it also increases service privilege and therefore requires continued configuration review.",
    futureImprovements: "Expand source coverage, document retention, validate Group Policy and DNS recovery, and publish reviewed evidence as each milestone completes.",
  },
  objectives: [
    "IMPLEMENTED — Establish a version-controlled engineering report, architecture baseline, and evidence standards.",
    "IN PROGRESS — Define segmented management, server, client, lab, and DMZ security zones with explicit trust boundaries.",
    "IMPLEMENTED — Deploy the first Windows Server domain controller with Active Directory Domain Services, internal DNS, organizational structure, separated administrative identities, and initial role-based groups.",
    "IMPLEMENTED — Deploy Sysmon and the Splunk Universal Forwarder across managed Windows systems and centralize retrievable telemetry in Splunk Enterprise.",
    "IN PROGRESS — Deploy DHCP, certificate, backup, and recovery services while extending telemetry coverage.",
    "IMPLEMENTED / PLANNED — Validate Windows telemetry delivery end to end; firewall policy, authentication, name resolution, address allocation, backup restoration, and recovery procedures retain their stated lifecycle.",
  ],
  overview: [
    "Project RedForge is developing a controlled enterprise environment for infrastructure administration, security engineering, monitoring, and incident-analysis practice. The current implementation includes the Microsoft identity foundation, a managed Windows endpoint, and centralized Splunk telemetry.",
    "The environment exists to support repeatable engineering scenarios, isolated testing, and traceable technical decisions without overstating production scale or unfinished capabilities.",
    "The project has established a documented identity baseline and verified end-to-end Windows telemetry retrieval. Network segmentation, member services, resilience, and broader detection coverage remain governed by their stated lifecycle.",
  ],
  technologies: [
    { name: "Documentation Baseline — Implemented", category: "platform", description: "Typed project record, editable diagrams, status taxonomy, and evidence placeholders are version controlled." },
    { name: "VMware Workstation Pro — Implemented", category: "platform", description: "Current virtualization platform hosting the first Windows Server identity workload." },
    { name: "Proxmox VE — Planned", category: "platform", description: "Target virtualization platform for Windows and Linux workloads; deployment evidence pending." },
    { name: "pfSense Firewall — Planned", category: "security", description: "Target routing, VLAN termination, policy enforcement, DHCP relay/service, VPN, and traffic logging role." },
    { name: "Management VLAN — In Progress", category: "infrastructure", description: "Designated administrative plane for hypervisor, firewall, and management interfaces." },
    { name: "Server VLAN — In Progress", category: "infrastructure", description: "Target zone for domain, certificate, logging, monitoring, and application services." },
    { name: "Client VLAN — In Progress", category: "infrastructure", description: "Target zone for managed Windows 11 workstations and user policy testing." },
    { name: "Lab VLAN — In Progress", category: "security", description: "Isolated target zone for Kali Linux, security tooling, and controlled testing." },
    { name: "DMZ — Planned", category: "security", description: "Restricted target zone for future externally exposed laboratory services." },
    { name: "Windows Server 2025 — Implemented", category: "infrastructure", description: "RF-DC01 hosts the implemented Active Directory Domain Services and internal DNS roles." },
    { name: "Linux Server — Planned", category: "infrastructure", description: "Target platform for infrastructure utilities, automation, and selected monitoring services." },
    { name: "Windows 11 — Implemented", category: "infrastructure", description: "RF-WIN11-01 participates in the verified Windows and Sysmon telemetry pipeline." },
    { name: "Kali Linux — Planned", category: "security", description: "Target isolated assessment workstation; use limited to authorized lab validation." },
    { name: "Active Directory Domain Services — Implemented", category: "security", description: "First forest and domain controller implemented with initial organizational structure and role-based groups." },
    { name: "DNS — Implemented", category: "infrastructure", description: "Internal DNS is operational on RF-DC01; resilience and recovery validation remain pending." },
    { name: "DHCP — Planned", category: "infrastructure", description: "Controlled address allocation remains a planned core-network capability." },
    { name: "Active Directory Certificate Services — Future", category: "security", description: "Future internal PKI for certificate enrollment, service identity, and trust testing." },
    { name: "Microsoft Sysmon — Implemented", category: "observability", description: "Standard endpoint instrumentation providing high-fidelity Windows security events on managed systems." },
    { name: "Splunk Universal Forwarder — Implemented", category: "observability", description: "Forwards Windows and Sysmon event channels from managed systems to the centralized platform." },
    { name: "Splunk Enterprise — Implemented", category: "observability", description: "Centralized indexing and SPL retrieval are validated for RF-DC01 and RF-WIN11-01 telemetry. Detection content and broader source onboarding remain planned." },
    { name: "Backup Repository — Planned", category: "infrastructure", description: "Target protected backup location with retention and restoration procedures." },
    { name: "Hybrid Cloud Connection — Future", category: "cloud", description: "Future controlled extension for cloud identity, logging, and network-security scenarios." },
  ],
  timeline: [
    { date: "Jul 2026", title: "Documentation and report platform", description: "IMPLEMENTED — Established the reusable project experience, typed content model, authoring standards, and editable SVG architecture package.", status: "complete" },
    { date: "Jul 22, 2026", title: "Enterprise blueprint completed", description: "COMPLETE — Reviewed the business, infrastructure, network, identity, security, operations, and documentation architecture package before implementation.", status: "complete" },
    { date: "Jul 22, 2026", title: "First identity server established", description: "IMPLEMENTED — Deployed RF-DC01 with Windows Server 2025, Active Directory Domain Services, internal DNS, initial organizational structure, separated administrative identities, and role-based groups. Screenshot evidence remains pending publication review.", status: "complete" },
    { date: "Jul 26, 2026", title: "Centralized telemetry pipeline operational", description: "IMPLEMENTED AND VERIFIED — Deployed Sysmon and the Splunk Universal Forwarder, centralized RF-DC01 and RF-WIN11-01 telemetry in Splunk Enterprise, remediated event-channel permissions, and retrieved controlled endpoint activity with SPL.", status: "complete" },
    { date: "Current", title: "Logical architecture and segmentation", description: "IN PROGRESS — Defining VLANs, trust boundaries, service dependencies, server inventory, and traffic-flow requirements.", status: "active" },
    { date: "Next", title: "Firewall and virtualization foundation", description: "PLANNED — Install the hypervisor and firewall, create initial networks, record configurations, and validate administrative access.", status: "planned" },
    { date: "Next", title: "Member server and file services", description: "PLANNED — Deploy the first member server, validate domain membership, and introduce group-governed file services.", status: "planned" },
    { date: "Next", title: "Threat hunting and detection foundations", description: "PLANNED — Develop reusable SPL investigations, dashboards, additional source onboarding, and controlled detection-validation scenarios.", status: "planned" },
    { date: "Future", title: "PKI, resilience, and hybrid cloud", description: "FUTURE — Evaluate AD CS, backup restoration exercises, recovery runbooks, and a controlled cloud connection.", status: "planned" },
  ],
  architecture: {
    summary: "IN PROGRESS — The target logical design places an Internet edge and firewall before DMZ, management, server, client, and lab VLANs. Identity and infrastructure services remain in the server zone; monitoring receives controlled telemetry across trust boundaries.",
    nodes: [
      { id: "internet", label: "Internet", type: "network", description: "EXTERNAL — Untrusted upstream network." },
      { id: "firewall", label: "Firewall", type: "security", description: "PLANNED — Routing, segmentation, policy, DHCP, VPN, and network logging." },
      { id: "dmz", label: "DMZ", type: "network", description: "PLANNED — Restricted zone for future published services." },
      { id: "management", label: "Management Network", type: "network", description: "IN PROGRESS — Administrative interfaces and controlled operator access." },
      { id: "server-vlan", label: "Server VLAN", type: "network", description: "IN PROGRESS — Identity, network, monitoring, and platform services." },
      { id: "client-vlan", label: "Client VLAN", type: "network", description: "IN PROGRESS — Managed Windows 11 workstations." },
      { id: "lab-vlan", label: "Lab VLAN", type: "network", description: "IN PROGRESS — Isolated Kali Linux and authorized test systems." },
      { id: "domain-controller", label: "RF-DC01 Domain Controller", type: "server", description: "IMPLEMENTED — Windows Server 2025 providing AD DS and internal DNS. Addressing is redacted." },
      { id: "dhcp", label: "DHCP Service", type: "service", description: "PLANNED — Scoped address allocation and option management." },
      { id: "certificate-authority", label: "Certificate Authority", type: "service", description: "FUTURE — Internal certificate enrollment and trust services." },
      { id: "splunk", label: "Splunk Enterprise", type: "security", description: "IMPLEMENTED — Centralized Windows and Sysmon ingestion and SPL retrieval are validated; dashboards and detections remain planned." },
      { id: "linux-server", label: "Linux Server", type: "server", description: "PLANNED — Utility, automation, and telemetry workload." },
      { id: "windows-client", label: "RF-WIN11-01 Workstation", type: "client", description: "IMPLEMENTED — Managed Windows endpoint forwarding Windows and Sysmon telemetry." },
      { id: "kali", label: "Kali Linux", type: "client", description: "PLANNED — Isolated authorized assessment endpoint." },
      { id: "cloud", label: "Future Cloud Connection", type: "cloud", description: "FUTURE — Controlled hybrid identity, logging, and network integration." },
    ],
    connections: [
      { from: "internet", to: "firewall", label: "Untrusted edge" },
      { from: "firewall", to: "dmz", label: "Restricted inbound policy" },
      { from: "firewall", to: "management", label: "Administrative policy" },
      { from: "firewall", to: "server-vlan", label: "Service policy" },
      { from: "firewall", to: "client-vlan", label: "User egress and service access" },
      { from: "firewall", to: "lab-vlan", label: "Isolated test policy" },
      { from: "server-vlan", to: "domain-controller", label: "AD DS and DNS" },
      { from: "server-vlan", to: "dhcp", label: "Address services" },
      { from: "server-vlan", to: "certificate-authority", label: "Future PKI" },
      { from: "client-vlan", to: "domain-controller", label: "Authentication and policy" },
      { from: "lab-vlan", to: "kali", label: "Authorized testing" },
      { from: "firewall", to: "splunk", label: "Network telemetry" },
      { from: "domain-controller", to: "splunk", label: "Identity and DNS logs" },
      { from: "windows-client", to: "splunk", label: "Validated endpoint telemetry" },
      { from: "server-vlan", to: "cloud", label: "Future hybrid connection" },
    ],
  },
  challenges: [
    { title: "Enterprise realism within finite resources", context: "IN PROGRESS — The target design must represent enterprise boundaries without claiming production scale or resilience.", resolution: "Use phased capacity planning, explicit workload priorities, resource reservations where justified, and evidence-based scaling decisions." },
    { title: "Service dependency sequencing", context: "IN PROGRESS — Identity, DNS, DHCP, PKI, logging, backup, and monitoring have ordering and recovery dependencies.", resolution: "Maintain a dependency map, deploy core network services before dependent workloads, and validate each phase before adding the next service." },
    { title: "Trust-boundary clarity", context: "IN PROGRESS — Permissive laboratory rules would reduce the value of segmentation exercises.", resolution: "Adopt default-deny inter-zone policy, document required flows, and approve exceptions against named services and validation cases." },
    { title: "Evidence without sensitive disclosure", context: "IMPLEMENTED — Engineering records must demonstrate work without exposing credentials, private addressing, secrets, or unsafe configurations.", resolution: "Use sanitized diagrams, redaction review, scoped screenshots, and placeholders until publishable evidence is available." },
    { title: "Sysmon event-channel access", context: "RESOLVED — RF-WIN11-01 generated Sysmon events locally, but the forwarding service could not initially subscribe to the Operational event channel.", resolution: "Structured troubleshooting isolated the permission boundary. Running the Universal Forwarder service under Local System restored collection without reinstalling the endpoint stack." },
  ],
  lessonsLearned: [
    { title: "Documentation is a control", insight: "IMPLEMENTED — Status-qualified records prevent planned capabilities from being represented as deployed or validated." },
    { title: "Boundaries precede workloads", insight: "IN PROGRESS — VLANs, administrative paths, and permitted flows should be defined before services are placed into zones." },
    { title: "Identity depends on foundational services", insight: "PLANNED VALIDATION — AD DS design must account for DNS, time synchronization, certificate, backup, and recovery dependencies." },
    { title: "Recovery claims require exercises", insight: "PLANNED VALIDATION — Backups alone do not demonstrate recoverability; restoration procedures and measured tests are required." },
    { title: "Telemetry requires end-to-end validation", insight: "IMPLEMENTED — Installation status is insufficient; known endpoint activity must be generated, forwarded, indexed, and retrieved before monitoring is considered operational." },
  ],
  gallery: [
    { src: "/projects/enterprise-home-lab/diagrams/network-topology.svg", alt: "Planned Enterprise Home Lab network topology showing Internet, firewall, DMZ, management, server, client, and lab security zones", caption: "IN PROGRESS — Target network topology and VLAN separation. This is a design artifact, not implementation evidence." },
    { src: "/projects/enterprise-home-lab/diagrams/logical-architecture.svg", alt: "Planned logical architecture showing identity, DNS, DHCP, certificate, logging, and monitoring services", caption: "IN PROGRESS — Logical service architecture with planned identity and observability dependencies." },
    { src: "/projects/enterprise-home-lab/diagrams/security-zones.svg", alt: "Planned security zones and trust boundaries for the Enterprise Home Lab", caption: "IN PROGRESS — Security-zone classification and intended trust boundaries." },
    { src: "/projects/enterprise-home-lab/diagrams/traffic-flow.svg", alt: "Planned traffic flows between client, identity, firewall, SIEM, and external services", caption: "PLANNED — Required traffic-flow categories; ports and rule identifiers await implementation." },
    { src: "/projects/enterprise-home-lab/diagrams/vlan-layout.svg", alt: "Planned VLAN layout for management, server, client, lab, and DMZ networks", caption: "IN PROGRESS — VLAN purpose model. VLAN identifiers and subnets remain placeholders." },
    { src: "/projects/enterprise-home-lab/diagrams/trust-boundaries.svg", alt: "Planned trust boundaries separating external, administrative, enterprise, and security-testing systems", caption: "IN PROGRESS — Trust-boundary model used to guide default-deny policy." },
    { src: "/projects/enterprise-home-lab/diagrams/rack-elevation.svg", alt: "Planned rack elevation showing firewall, virtualization host, switching, backup, and reserved capacity", caption: "PLANNED — Conceptual rack elevation; hardware units and placement are not implementation evidence." },
    { src: "/projects/enterprise-home-lab/diagrams/hybrid-cloud.svg", alt: "Future hybrid cloud layout connecting the laboratory firewall and server network to a cloud environment", caption: "FUTURE — Conceptual cloud connection reserved for a later approved phase." },
    { alt: "Enterprise Home Lab firewall configuration screenshot placeholder", caption: "PLACEHOLDER — Real firewall configuration evidence will be added after implementation and redaction review." },
    { alt: "Enterprise Home Lab server inventory screenshot placeholder", caption: "PLACEHOLDER — Real virtualization and server inventory evidence has not been captured." },
    { alt: "Enterprise Home Lab Splunk telemetry screenshot pending publication review", caption: "EVIDENCE PENDING — Telemetry ingestion is validated in ENG-010, but supporting screenshots remain outside the public pipeline until asset-level security and privacy review is complete." },
  ],
  videos: [
    { title: "Architecture review", description: "PLANNED — A guided design review will be recorded after architecture approval." },
    { title: "Implementation walkthrough", description: "PLACEHOLDER — No deployment walkthrough exists because the infrastructure milestone is not complete." },
  ],
  codeExamples: [{
    title: "Planned validation manifest",
    language: "yaml",
    description: "DESIGN EXAMPLE — A proposed machine-readable inventory for future connectivity validation; not executed evidence.",
    code: "environment: enterprise-home-lab\nstatus: planned\nzones:\n  - management\n  - server\n  - client\n  - lab\n  - dmz\nchecks:\n  - dns-resolution\n  - dhcp-allocation\n  - identity-authentication\n  - telemetry-delivery\n  - backup-restoration\n",
  }],
  downloads: [
    { title: "Network topology SVG", description: "Editable RedForge target-state network topology.", format: "SVG", url: "/projects/enterprise-home-lab/diagrams/network-topology.svg" },
    { title: "Logical architecture SVG", description: "Editable identity, infrastructure, and monitoring service design.", format: "SVG", url: "/projects/enterprise-home-lab/diagrams/logical-architecture.svg" },
    { title: "Microsoft AD DS overview", description: "Official reference for Active Directory Domain Services concepts.", format: "Reference", url: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/active-directory-overview" },
    { title: "Microsoft AD CS overview", description: "Official reference for future certificate-services design.", format: "Reference", url: "https://learn.microsoft.com/en-us/windows-server/identity/ad-cs/active-directory-certificate-services-overview" },
    { title: "Netgate VLAN documentation", description: "Official reference for planned pfSense VLAN configuration.", format: "Reference", url: "https://docs.netgate.com/pfsense/en/latest/vlan/index.html" },
    { title: "Proxmox VE administration guide", description: "Official platform administration reference.", format: "Reference", url: "https://pve.proxmox.com/pve-docs/pve-admin-guide.pdf" },
    { title: "Splunk Enterprise documentation", description: "Official reference supporting the implemented centralized telemetry platform and its planned expansion.", format: "Reference", url: "https://docs.splunk.com/Documentation/Splunk/latest/Admin/StartSplunk" },
  ],
  certifications: [{ name: "CompTIA Network+", issuer: "CompTIA" }, { name: "Microsoft Windows Server", issuer: "Microsoft Learn" }],
  futureRoadmap: [
    "IN PROGRESS — Approve VLAN purposes, trust boundaries, dependency map, and traffic-flow matrix.",
    "PLANNED — Install and baseline the firewall and virtualization platform with sanitized configuration records.",
    "IN PROGRESS — Extend the implemented RF-DC01 identity and DNS foundation with DHCP, the first member server, and a managed Windows 11 workstation.",
    "IN PROGRESS — Extend the verified Windows telemetry pipeline with additional sources, documented retention, dashboards, and detection content.",
    "PLANNED — Implement protected backups, document restoration order, and execute recovery exercises before stating recovery capability.",
    "FUTURE — Evaluate AD CS, DMZ workloads, additional domain-controller resilience, vulnerability management, and hybrid cloud connectivity.",
  ],
  relatedProjectSlugs: ["active-directory-lab", "splunk-detection-lab", "network-engineering"],
};

const legacyProjects = [
  enterpriseHomeLab,
  plannedProject("active-directory-lab", "Active Directory Lab", "Identity, policy, authentication, and administrative controls.", [{ name: "Windows Server — Planned", category: "infrastructure" }]),
  plannedProject("splunk-detection-lab", "Splunk Detection Lab", "Telemetry ingestion, investigation, dashboards, and detection workflows.", [{ name: "Splunk telemetry foundation — Implemented", category: "observability", description: "Centralized Windows and Sysmon ingestion is operational; detection engineering remains planned." }]),
  plannedProject("python-automation", "Python Automation", "Operational tooling, validation, and repeatable engineering workflows.", [{ name: "Python — Planned", category: "automation" }]),
  plannedProject("aws-security", "AWS Security", "Cloud identity, logging, networking, and least-privilege engineering.", [{ name: "AWS — Planned", category: "cloud" }]),
  plannedProject("threat-hunting", "Threat Hunting", "Evidence-driven investigation and defensible analytical conclusions.", [{ name: "Splunk — Planned", category: "observability" }]),
  plannedProject("vulnerability-management", "Vulnerability Management", "Asset visibility, prioritization, remediation, and validation.", [{ name: "Nessus — Planned", category: "security" }]),
  plannedProject("network-engineering", "Network Engineering", "Routing, segmentation, services, and resilient network operations.", [{ name: "pfSense — Planned", category: "infrastructure" }]),
] satisfies readonly Project[];

export const projects = [
  currentEnterpriseHomeLab(enterpriseHomeLab),
  enterpriseActiveDirectory,
  enterpriseSecurityMonitoring,
  ...legacyProjects.filter((project) =>
    !["enterprise-home-lab", "active-directory-lab", "splunk-detection-lab"].includes(project.slug),
  ),
] satisfies readonly Project[];

export type ProjectSlug = (typeof projects)[number]["slug"];

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
