const banner = `// AUTO-GENERATED BY npm run content:sync.
// DO NOT EDIT MANUALLY. Update the reviewed Obsidian source and synchronize again.
// This file must remain committed so production builds never require the local vault.
`;

export function renderGeneratedModule(entries) {
  return `${banner}
import type { DocumentationEntry } from "./types";

export const generatedDocumentationEntries = ${JSON.stringify(entries, null, 2)} as const satisfies readonly DocumentationEntry[];
`;
}

